(define (solve)
  (let ((betty (amb 1 2 3 4 5))
        (ethel (amb 1 2 3 4 5))
        (joan (amb 1 2 3 4 5))
        (kitty (amb 1 2 3 4 5))
        (mary (amb 1 2 3 4 5)))
    (require (distinct? (list betty ethel joan kitty mary)))
    (require (nandor (= kitty 2) (= betty 3)))
    (require (nandor (= ethel 1) (= joan 2)))
    (require (nandor (= joan 3) (= ethel 5)))
    (require (nandor (= kitty 2) (= mary 4)))
    (require (nandor (= mary 4) (= betty 1)))
    (list (list 'betty betty)
          (list 'ethel ethel)
          (list 'joan joan)
          (list 'kitty kitty)
          (list 'mary mary))))

(define (nandor x y) (or (and x (not y)) (and (not x) y)))

(define (require p)
  (if (not (true? p)) (amb)))

(define (distinct? items)
  (cond ((null? items) true)
        ((null? (cdr items)) true)
        ((member (car items) (cdr items)) false)
        (else (distinct? (cdr items)))))
