(define (make-account balance password)
	(let ((failed-access 0))
		(define (withdraw amount)
			(if (>= balance amount)
				(begin (set! balance (- balance amount))
							 balance)
				(error "Insufficient funds")))
		(define (deposit amount)
			(set! balance (+ balance amount))
			balance)
		(define (dispatch pass m)
			(if (eq? password pass)
				(cond ((eq? m 'withdraw) withdraw)
							((eq? m 'deposit) deposit)
							(else (error "Unknown request -- MAKE-ACCOUNT" m)))
				(begin (set! failed-access (+ failed-access 1))
							 (and (>= failed-access 7) (call-the-cops))
							 (error "The password is not correct" pass))))
		(define (call-the-cops)
			(display "Call the cops")
			(newline))
		dispatch))
