(define (make-account balance password)
	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
						 balance)
			(error "Insufficient funds")))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (dispatch pass m)
		(if (eq? password pass)
			(cond ((eq? m 'withdraw) withdraw)
						((eq? m 'deposit) deposit)
						(else (error "Unknown request -- MAKE-ACCOUNT" m)))
			(error "The password is not correct" pass)))
	dispatch)

(define (make-joint account account-password joint-password)
 (define (dispatch pass m)
	(if (eq? pass joint-password)
	 (account account-password m)
	 (error "Incorrect password for joint account" pass)))
 dispatch)

(define (make-joint account account-password joint-password)
	(lambda (pass m)
		(if (eq? pass joint-password)
			(account account-password m)
			(error "Incorrect password for joint account" pass))))
