(load "./chap3/circuit.scm")

(define (or-gate a1 a2 output)
	(let ((c (make-wire))
				(d (make-wire))
				(e (make-wire)))
		(inverter a c)
		(inverter b d)
		(and-gate c d e)
		(inverter e output)
		'ok))
